# https://rhysd.github.io/actionlint/
name: SB-lab CI
on:
  push:
    branches: [prod-front]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        if: always()
        run: npm run build:prod
      - name: TEST eslint...
        if: always()
        run: npm run eslint
      - name: TEST stylelint...
        if: always()
        run: npm run stylelint
      - name: TEST unit test
        if: always()
        run: npm run unit
      # - name: build storybook...
      #   if: always()
      #   run: npm run sb:build
      # - name: ui screenshot test...
      #   if: always()
      #   run: npm run ui
